---
- name: Create Container of app
  hosts: all
  tasks:
    - name: web container
      docker_container:
        name: testcalci
        image: sanir456/scientific-calculator-devopstools-webapp
        state: started
        ports:
          - "8085:8085"
        tty: true
        detach: true