---
- name: Create Container of app
  hosts: all
  tasks:
    - name: web container
      docker_container:
        name: testcalci
        image: ehrazhasan/scientificalculator
        state: started
        ports:
          - "8081:8081"
        tty: true
        detach: true